<a href="https://colab.research.google.com/github/leonardosanch/OPENCV/blob/main/Keras2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
from numpy import genfromtxt
data = genfromtxt('/content/bank_note_data.txt' , delimiter=',')

In [4]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [6]:
etiquetas=data[:,4]

In [7]:
caracteristicas = data[:,0:4]

In [8]:
X = caracteristicas
y = etiquetas

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.33, random_state=42)

# Normalizar

In [11]:
from sklearn.preprocessing import MinMaxScaler

In [12]:
scaler_object = MinMaxScaler()

In [13]:
scaler_object.fit(X_train)

MinMaxScaler()

In [14]:
scaled_X_train = scaler_object.transform(X_train)

In [15]:
scaled_X_test = scaler_object.transform(X_test)

In [ ]:
# empezar a construir el modelo

In [16]:
from keras.models import Sequential
from keras.layers import Input, Dense



In [17]:
model = Sequential()
model.add(Dense(4, input_dim=4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))


In [18]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
#Entrenar el modelo

In [21]:
model.fit(scaled_X_train, y_train, epochs=100, verbose=2)

Epoch 1/100
29/29 - 0s - loss: 0.1335 - accuracy: 0.9565 - 49ms/epoch - 2ms/step
Epoch 2/100
29/29 - 0s - loss: 0.1311 - accuracy: 0.9587 - 48ms/epoch - 2ms/step
Epoch 3/100
29/29 - 0s - loss: 0.1281 - accuracy: 0.9554 - 52ms/epoch - 2ms/step
Epoch 4/100
29/29 - 0s - loss: 0.1254 - accuracy: 0.9587 - 49ms/epoch - 2ms/step
Epoch 5/100
29/29 - 0s - loss: 0.1230 - accuracy: 0.9587 - 50ms/epoch - 2ms/step
Epoch 6/100
29/29 - 0s - loss: 0.1204 - accuracy: 0.9608 - 49ms/epoch - 2ms/step
Epoch 7/100
29/29 - 0s - loss: 0.1180 - accuracy: 0.9597 - 47ms/epoch - 2ms/step
Epoch 8/100
29/29 - 0s - loss: 0.1164 - accuracy: 0.9608 - 57ms/epoch - 2ms/step
Epoch 9/100
29/29 - 0s - loss: 0.1134 - accuracy: 0.9641 - 58ms/epoch - 2ms/step
Epoch 10/100
29/29 - 0s - loss: 0.1115 - accuracy: 0.9630 - 49ms/epoch - 2ms/step
Epoch 11/100
29/29 - 0s - loss: 0.1097 - accuracy: 0.9652 - 49ms/epoch - 2ms/step
Epoch 12/100
29/29 - 0s - loss: 0.1077 - accuracy: 0.9641 - 49ms/epoch - 2ms/step
Epoch 13/100
29/29 - 0s -

In [23]:
predictions= model.predict(scaled_X_test)

15/15 [==============================] - 0s 2ms/step


In [24]:
classes =(predictions>0.5).astype(int)

In [25]:
classes

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    

In [26]:
model.metrics_names

['loss', 'accuracy']

In [27]:
model.evaluate(x=scaled_X_test, y=y_test)

15/15 [==============================] - 0s 3ms/step - loss: 0.0422 - accuracy: 0.9868


[0.04220576584339142, 0.9867549538612366]

In [31]:
from sklearn.metrics import confusion_matrix, classification_report

In [32]:
confusion_matrix(y_test, classes)

array([[253,   4],
       [  2, 194]])

In [35]:
print(classification_report(y_test, classes))

              precision    recall  f1-score   support

         0.0       0.99      0.98      0.99       257
         1.0       0.98      0.99      0.98       196

    accuracy                           0.99       453
   macro avg       0.99      0.99      0.99       453
weighted avg       0.99      0.99      0.99       453



In [36]:
model.save('mimodelo.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [37]:
from keras.models import load_model

In [39]:
nuevo_modelo = load_model('mimodelo.h5')

In [40]:
nuevo_modelo.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 20        
                                                                 
 dense_1 (Dense)             (None, 8)                 40        
                                                                 
 dense_2 (Dense)             (None, 1)                 9         
                                                                 
Total params: 69 (276.00 Byte)
Trainable params: 69 (276.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
